fix lint, see below:
```text
error[E0063]: missing fields `rejected` and `soft_fail` in initializer of `rezzy::LeanEvent<_, _>`
    --> src/service/rooms/state_res/resolve/tests.rs:1190:2
     |
1190 |     rezzy::LeanEvent {
     |     ^^^^^^^^^^^^^^^^ missing `rejected` and `soft_fail`

For more information about this error, try `rustc --explain E0063`.
```